apiVersion: v1
kind: Service
metadata:
  name: hashicat-service
  labels:
    app: hashicat
    version: v1
spec:
  selector:
    app: hashicat
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort