apiVersion: v1
kind: Service
metadata:
  name: hashicat-web-v2
  labels:
    app: hashicat-web-v2
    version: v2
spec:
  selector:
    app: hashicat-web
    version: v2
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: NodePort