apiVersion: v1
kind: Service
metadata:
  name: hashicat-metadata
  labels:
    app: hashicat-metadata
    version: v1
spec:
  selector:
    app: hashicat-metadata
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 9090
  type: ClusterIP