apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicat-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicat-web
  template:
    metadata:
      labels:
        app: hashicat-web
        version: v1
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'hashicat-url:80, hashicat-metadata:80'
    spec:
      containers:
        - name: hashicat-web
          image: kawsark/hashicat-web:0.0.1
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: "True"
            - name: URLSERVICE_URI
              value: "http://127.0.0.1"
            - name: METADATA_URI
              value: "http://127.0.0.1"
          ports:
          - containerPort: 5000