apiVersion: v1
kind: Service
metadata:
  name: hashicat-web
  labels:
    app: hashicat-web
    version: v1
spec:
  selector:
    app: hashicat-web
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: NodePort